### ISSUE TITLE
Error in Fbad_request

### ISSUE THREAD

**Issue by bofrmar** [daroczig/fbRads#54] opened 2017-04-20 18:05 UTC
Hello,

I run a R studio script on a daily basis and as of yesterday I encountered an error while running the script. This is what I get:

Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
 This is a bug in the fbRads package. Please report on GitHub with a detailed output: SSL certificate problem: self signed certificate in certificate chain

Any ideas of what the issue might be?

Thanks in advance

**Comment by daroczig** [comment] 2017-04-20 19:56
Sometimes there's a temporary connection or SSL issue, which should be resolved in a few mins at Facebook's end. Can you please confirm it's an ongoing issue or was resolved since then?

**Comment by bofrmar** [comment] 2017-04-20 20:11
This is an ongoing issues since yesterday.

**Comment by daroczig** [comment] 2017-04-20 20:12
Are you using v2.8 or still on v2.7? Can you share the command generating this error message and a full traceback?

**Comment by bofrmar** [comment] 2017-04-20 20:20
I am not very technical or an expert in R scripts, but this is what I could find:

```r
fbad_init(accountid = account_id, token = fbtkn, version = '2.8')
startdate <- Sys.Date() - if(as.POSIXlt(Sys.Date())$wday == 1) {
  3
}  else {
  1
}
enddate <- Sys.Date() - 1
```

**Comment by daroczig** [comment] 2017-04-20 20:24
Can you please share your session info? Just run `sessionInfo()` or if you have `devtools` installed, then `devtools::session_info()`

**Comment by bofrmar** [comment] 2017-04-20 20:30
insight <- fb_insights(time_range = toJSON(list(
                                                since = as.character(startdate),
                                                until = as.character(enddate))),
                       time_increment = 1, level = 'ad', 
                       fields = toJSON(c('date_start','date_stop','account_id','campaign_id','campaign_name','adset_id',
                                         'ad_id','impressions','unique_impressions','clicks',
                                         'total_actions','spend')))

**Comment by bofrmar** [comment] 2017-04-20 21:46
Sorry, here you go:
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.6.1   dplyr_0.5.0   rjson_0.2.15  rlist_0.4.6.1 jsonlite_1.3  fbRads_0.2   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10         assertthat_0.1       digest_0.6.12        bitops_1.0-6         R6_2.2.0            
 [6] plyr_1.8.4           futile.options_1.0.0 DBI_0.6              magrittr_1.5         data.table_1.10.4   
[11] futile.logger_1.4.3  lambda.r_1.1.9       tools_3.3.3          bit64_0.9-5          RCurl_1.95-4.8      
[16] bit_1.1-12           tibble_1.2

**Comment by daroczig** [comment] 2017-04-20 23:22
Can you try updating cacert.pem to the most recent one found at https://curl.haxx.se/ca/cacert.pem ?

To find the currently installed cacert.pem on your computer, run this in R:

```r
system.file('CurlSSL', 'cacert.pem', package = 'RCurl')
```

Then once you know the file path, download the above file from curl.haxx.se, overwrite the old one and retry the script. I think this issue is related to the outdated cacert.pem

**Comment by bofrmar** [comment] 2017-04-21 00:09
This didn't work, I also tried installing RCurl again but no success. Any other ideas?


> fbad_init(accountid = account_id, token = fbtkn, version = '2.8')
ERROR [2017-04-20 17:03:40] URL: ?????
ERROR [2017-04-20 17:03:40] Method:  GET
ERROR [2017-04-20 17:03:40] Params:  List of 1
 $ fields: chr "name,account_id,account_status,age,amount_spent,balance,capabilities,end_advertiser,funding_source,spend_cap,timezone_id,users"
Error in fbad_request(path = paste0("act_", accountid, "/"), method = "GET",  : 
  This is a bug in the fbRads package. Please report on GitHub with a detailed output: SSL certificate problem: self signed certificate in certificate chain
>

**Comment by daroczig** [comment] 2017-04-21 11:03
That's odd. Any chance you are behind a firewall/proxy that adds a man in the middle cert?

**Comment by bofrmar** [comment] 2017-04-21 15:57
Actually this might be. Its interesting because it was working fine, something might have changed in the firewall/proxy.

**Comment by daroczig** [comment] 2017-04-21 19:26
Can you please confirm with the IT folks? Please let me know what you find, and I'll try to reproduce this locally if that's not the case.

**Comment by bofrmar** [comment] 2017-04-24 17:20
IT is looking into the issue. Seems like there was a changed in the firewall. Will keep you updated.

I am seeing a similar issue in the curl package. Do you think this might be the firewall change as well?

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)

**Comment by daroczig** [comment] 2017-05-03 19:47
Do you have any update from the IT team?

**Comment by bofrmar** [comment] 2017-05-03 19:52
Yes, the issue with the fbRads package was related to a change in our firewall. Thanks for the help

**Comment by daroczig** [comment] 2017-05-03 19:58
Cool, thanks a lot for the feedback.

**Closed as completed by daroczig** 2017-05-03 19:58 UTC
Labels: more information needed
