### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by caiogoncalves** [daroczig/fbRads#41] opened 2017-01-31 15:28 UTC
Hi, i'm getting this estrange output in my script 

>  This is a bug in the fbRads package. Please report on GitHub with a detailed output: Failed to connect to graph.facebook.com port 443: Timed out

**Comment by daroczig** [comment] 2017-01-31 18:29
Thanks a lot for reporting this. It seems to me that it was due to a network error (either on your end, or at FB -- which happens by the way), so I'm closing this, but please reopen if you can reproduce the problem on an ongoing basis.

**Closed as completed by daroczig** 2017-01-31 18:29 UTC
